# Generated by Django 4.1.2 on 2023-03-01 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProductApp', '0009_alter_productdetails_manufacturer_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='productdetails',
            table=None,
        ),
    ]
